# frozen_string_literal: true

module Gat
  class Executor
    REPORT_SHEET_NAME = "System export"
    attr_reader :spreadsheet, :spreadsheet_id

    def initialize(service, spreadsheet_id)
      @spreadsheet_id = spreadsheet_id
      @spreadsheet = GoogleSpreadSheet.new(service, spreadsheet_id)
    end

    def upload_to_google_sheets(report)
      return unless spreadsheet_id

      spreadsheet.write_to("status", status_msg(:in_process))

      spreadsheet.write_to(REPORT_SHEET_NAME, report)

      spreadsheet.write_to("status", status_msg(:done))
    end

    def status_msg(status) # rubocop:disable Metrics/MethodLength
      [
        ["THIS SPREADSHEET IS AUTOMATICALLY GENERATED BY THE SELMA SYSTEM. DO NOT MANUALLY EDIT THIS SPREADSHEET."]
      ].tap do |data|
        case status
        when :in_process
          data.push(["Uploading data in progress since… #{Time.now}"])
        when :done
          data.push(["Data uploaded successfully on #{Time.now}"])
        else
          raise "Unkown Status"
        end
      end
    end
  end


end
